---
name: Build and Deploy

env:
  CNAME: www.lukestigdon.com
  ODIR: dist

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn build
      - name: deploy
        run: |
          echo $CNAME > $ODIR/CNAME
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f $ODIR
          git commit -m 'deploy'
          git filter-branch --subdirectory-filter $ODIR -- --all
          git push -f origin gh-pages
