---
name: Build and Deploy

env:
  CNAME: www.lukestigdon.com
  ODIR: dist

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn build
      - name: deploy
        run: |
          cd $ODIR
          echo $CNAME > CNAME
          git config --global init.defaultBranch "main"
          git config --global user.email "lstig@users.noreply.github.com"
          git config --global user.name "Luke Stigdon"
          git init
          git add -A
          git commit -m 'deploy'
          git push -f $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git main:gh-pages
